// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Use hardcoded values for JavaScript build
const SUPABASE_URL = "https://ryhjupukuxjclwmmkknn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5aGp1cHVrdXhqY2x3bW1ra25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzU1MDcsImV4cCI6MjA3NDA1MTUwN30.3gqqr18l-GD2hXNWtL6Gp2_URaPtC-75d9_V6FWl4u4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});